-- Generado desde el ATH del prototipo (docs/APP_CLUB_prototipo.html).
-- Los 12 marcados "Sin asignar" son los que aun no tienen fecha de nacimiento
-- ni grupo real confirmado (ver docs/QUE_CONSTRUIR.md, bloqueos pendientes).
-- Pegar en Supabase > SQL Editor > Run. Es idempotente: si ya existe el ref
-- (unique), no duplica.
insert into deportistas (ref, nombre, categoria, grupo_id) values
  ('D001', 'Airam Giuseppi Perales Mayta', 'Infantil', (select id from grupos where nombre = 'Intermedio')),
  ('D002', 'Alba García Palacios', 'Infantil', (select id from grupos where nombre = 'Intermedio')),
  ('D003', 'Alba Marfil Gómez', 'Alevin', (select id from grupos where nombre = 'Peques')),
  ('D004', 'Alejandro Martín-Velasco Suárez', 'Cadete', (select id from grupos where nombre = 'Intermedio')),
  ('D005', 'ALICIA DELGADO HUERTAS', 'Juvenil', (select id from grupos where nombre = 'Avanzado')),
  ('D006', 'Alonso García Palacios', 'Benjamin', (select id from grupos where nombre = 'Escuela jueves')),
  ('D007', 'Anaïs Rodriguez Bastiani', 'Cadete', (select id from grupos where nombre = 'Intermedio')),
  ('D008', 'Bruno Pasamontes alarcon', 'Alevin', (select id from grupos where nombre = 'Peques')),
  ('D009', 'Carlos Pereda Lostau', 'Benjamin', (select id from grupos where nombre = 'Escuela jueves')),
  ('D010', 'Celia Pereda Lostau', 'Alevin', (select id from grupos where nombre = 'Peques')),
  ('D011', 'Cleoma Bonvalet', 'Cadete', (select id from grupos where nombre = 'Intermedio')),
  ('D012', 'Daniel Bárez Carballo', 'Cadete', (select id from grupos where nombre = 'Intermedio')),
  ('D013', 'david', 'Alevin', (select id from grupos where nombre = 'Peques')),
  ('D014', 'Eloy Bárez Carballo', 'Alevin', (select id from grupos where nombre = 'Peques')),
  ('D015', 'Gorka Hernando Muñoz', 'Infantil', (select id from grupos where nombre = 'Intermedio')),
  ('D016', 'Guillermo González Serralta', 'Infantil', (select id from grupos where nombre = 'Intermedio')),
  ('D017', 'Hugo Jiménez Ocaña', 'Alevin', (select id from grupos where nombre = 'Peques')),
  ('D018', 'Hugo Ramos Gonzalez', 'Infantil', (select id from grupos where nombre = 'Intermedio')),
  ('D019', 'Hugo Simon Perez', 'Infantil', (select id from grupos where nombre = 'Intermedio')),
  ('D020', 'Isabel Simpson', 'Cadete', (select id from grupos where nombre = 'Intermedio')),
  ('D021', 'JAIME CONTRERAS LOPEZ', 'Cadete', (select id from grupos where nombre = 'Intermedio')),
  ('D022', 'Jara Lahera Sánchez', 'Infantil', (select id from grupos where nombre = 'Intermedio')),
  ('D023', 'Jorge del Río Serrano', 'Alevin', (select id from grupos where nombre = 'Peques')),
  ('D024', 'Julia Millo Bretin', 'Cadete', (select id from grupos where nombre = 'Intermedio')),
  ('D025', 'Lola López Moreno', 'Benjamin', (select id from grupos where nombre = 'Escuela jueves')),
  ('D026', 'Lucia Simon Perez', 'Infantil', (select id from grupos where nombre = 'Intermedio')),
  ('D027', 'Luna González Serralta', 'Benjamin', (select id from grupos where nombre = 'Escuela jueves')),
  ('D028', 'Mario tejero maria', 'Prebenjamin', (select id from grupos where nombre = 'Escuela jueves')),
  ('D029', 'Martina Pous Ribagorda', 'Cadete', (select id from grupos where nombre = 'Intermedio')),
  ('D030', 'Martín Arribas del Amo', 'Alevin', (select id from grupos where nombre = 'Peques')),
  ('D031', 'María Caballero de la Cruz', 'Cadete', (select id from grupos where nombre = 'Intermedio')),
  ('D032', 'María Simpson', 'Alevin', (select id from grupos where nombre = 'Peques')),
  ('D033', 'Quique López Moreno', 'Infantil', (select id from grupos where nombre = 'Intermedio')),
  ('D034', 'Sarasvati Delis Rojas', 'Infantil', (select id from grupos where nombre = 'Intermedio')),
  ('D035', 'Saul', 'Infantil', (select id from grupos where nombre = 'Intermedio')),
  ('D036', 'Saúl Niño Negreira', 'Benjamin', (select id from grupos where nombre = 'Escuela jueves')),
  ('D037', 'TULIO RUIZ DELGADO', 'Benjamin', (select id from grupos where nombre = 'Escuela jueves')),
  ('D038', 'Vega Delgado de Felix', 'Alevin', (select id from grupos where nombre = 'Peques')),
  ('D039', 'Alejandro Sanchez', 'Absoluto', (select id from grupos where nombre = 'Adultos competición')),
  ('D040', 'Andreína Maris', 'Absoluto', (select id from grupos where nombre = 'Adultos competición')),
  ('D041', 'angel', '?', null),
  ('D042', 'Angelina', '?', null),
  ('D043', 'Carolina Sánchez perez', '?', null),
  ('D044', 'Daniel Caballero', 'Junior', (select id from grupos where nombre = 'Avanzado')),
  ('D045', 'Daniel Castro Márquez', 'Absoluto', (select id from grupos where nombre = 'Adultos competición')),
  ('D046', 'Daniel Puche Hontanilla', 'Veterano', (select id from grupos where nombre = 'Adultos competición')),
  ('D047', 'David del Río Pascual', 'Veterano', (select id from grupos where nombre = 'Adultos competición')),
  ('D048', 'Diego Gil', 'Junior', (select id from grupos where nombre = 'Avanzado')),
  ('D049', 'Elena Perez Ruiz', 'Veterano', (select id from grupos where nombre = 'Adultos competición')),
  ('D050', 'Fernando Niño Martínez', 'Veterano', (select id from grupos where nombre = 'Adultos competición')),
  ('D051', 'Hermano Rosa', '?', null),
  ('D052', 'Hugo Martin Rodao', 'Sub23', (select id from grupos where nombre = 'Avanzado')),
  ('D053', 'isabela', '?', null),
  ('D054', 'Joaquín Millo Acedo', 'Veterano', (select id from grupos where nombre = 'Adultos competición')),
  ('D055', 'José Luis Martín-VelascoGutiérrez', 'Veterano', (select id from grupos where nombre = 'Adultos competición')),
  ('D056', 'José Luis Plaza Canga-Arguelles', 'Veterano', (select id from grupos where nombre = 'Adultos competición')),
  ('D057', 'Lara de Diego Gustin', 'Absoluto', (select id from grupos where nombre = 'Adultos competición')),
  ('D058', 'lucas', '?', null),
  ('D059', 'Luis Cerrillo Arias', 'Veterano', (select id from grupos where nombre = 'Adultos competición')),
  ('D060', 'Luis Miguel Blázquez Iznaol', 'Veterano', (select id from grupos where nombre = 'Adultos competición')),
  ('D061', 'Manuel Arenas Mateos', 'Absoluto', (select id from grupos where nombre = 'Adultos competición')),
  ('D062', 'Marta', '?', null),
  ('D063', 'Miguel Angel Contreras Contreras', 'Veterano', (select id from grupos where nombre = 'Adultos competición')),
  ('D064', 'Miguel Ángel Pedrosa Hiruelas', 'Veterano', (select id from grupos where nombre = 'Adultos competición')),
  ('D065', 'Noa', '?', null),
  ('D066', 'Noemí de la Cuerda', 'Veterano', (select id from grupos where nombre = 'Adultos competición')),
  ('D067', 'Paloma Canales Espi', 'Absoluto', (select id from grupos where nombre = 'Adultos competición')),
  ('D068', 'Paloma Rojas Vaquero', 'Veterano', (select id from grupos where nombre = 'Adultos competición')),
  ('D069', 'paula', '?', null),
  ('D070', 'Paula Holguín Segovia', 'Absoluto', (select id from grupos where nombre = 'Adultos competición')),
  ('D071', 'Peter Simpson', 'Veterano', (select id from grupos where nombre = 'Adultos competición')),
  ('D072', 'Rafael Caballero de la Cruz', 'Veterano', (select id from grupos where nombre = 'Adultos competición')),
  ('D073', 'Raquel Gómez García', 'Veterano', (select id from grupos where nombre = 'Adultos competición')),
  ('D074', 'Rosa', '?', null),
  ('D075', 'Rosa Negreira Hernandez', 'Veterano', (select id from grupos where nombre = 'Adultos competición')),
  ('D076', 'Sandra Machado Henares', 'Veterano', (select id from grupos where nombre = 'Adultos competición')),
  ('D077', 'sergio', '?', null),
  ('D078', 'Sonia Andres Conde', 'Veterano', (select id from grupos where nombre = 'Adultos competición')),
  ('D079', 'Teresa Serralta Gely', 'Absoluto', (select id from grupos where nombre = 'Adultos competición')),
  ('D080', 'youleth', '?', null)
on conflict (ref) do update set
  nombre    = excluded.nombre,
  categoria = excluded.categoria,
  grupo_id  = excluded.grupo_id;
