-- Carga del histórico completo de inscripciones (Google Sheet, hoja
-- "Respuestas de formulario 1"), revisión 20/08/2026. Seguro de repetir:
-- no duplica a quien ya tenga una fila con el mismo nombre completo (por
-- ejemplo los que ya entraron por el webhook en vivo estos días).
--
-- Aviso: unas pocas filas del Excel original tienen columnas
-- desplazadas de fábrica (ej. un teléfono metido en la casilla de "días
-- piscina") — se ha cargado tal cual viene, revisa a mano en la sección
-- de Inscripciones (dentro de Administración) las que veas raras si te
-- importa el detalle para esa persona en concreto.

with datos(email, nombre_completo, dni, fecha_nacimiento, domicilio,
           talla_camiseta, dias_piscina, proteccion_datos, derechos_imagen,
           telefono, email2, tarifa) as (
  values
  ('grace1520@hotmail.com', 'Airam Giuseppi Perales Mayta', '51264234V', '2013-09-26', 'C/ Virgen de la Jarosa, 22 casa 1B Guadarrama', 'XS', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '638196924', 'Grace1520@hotmail.com', '440'),
  ('soniadue81@gmail.com', 'Alba García Palacios', '11088273L', '2014-04-29', 'Paseo de la Cañada 11. Galapagar', '12 años', 'MARTES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '667633603', 'soniadue81@gmail.com', '440'),
  ('raquelgg84@hotmail.com', 'Alba Marfil Gómez', '30332887G', '2016-07-05', 'Calle A Coruña número 4 Alpedrete', '10 años', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '660040550', 'raquelgg84@hotmail.com', '440'),
  ('alejandro.marvelsu@gmail.com', 'Alejandro Martín-Velasco Suárez', '02783973F', '2011-10-23', 'Calle Roma 3, portal 3, 1D, Alpedrete, Madrid', 'M', 'JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '629428920', 'alejandro.marvelsu@gmail.com', '440'),
  ('asanchezmartin89@gmail.com', 'Alejandro Sanchez Martin', '44917021e', '1989-08-08', 'urb. alto de la jarosa casa 24 guadarrama', 'L', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '667301593', 'asanchezmartin89@gmail.com', '440'),
  ('aliciadelgado.co@gmail.com', 'ALICIA DELGADO PRIETO', '54367526B', '2010-02-16', 'Calle Prado Rubia 9 Navacerrada', 'M', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '620594561', 'aliciadelgado.co@gmail.com', '440'),
  ('soniadue81@gmail.com', 'Alonso García Palacios', '12838208E', '2018-05-08', 'Paseo de la Cañada, 11 galapagar', '8 años', 'JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '667633603', 'soniadue81@gmail.com', '440'),
  (null, 'ana Carmen Pozo Pascual', '70051381m', '1979-02-06', 'ciudad real 11 guadarrama', null, null, null, null, '652813817', 'anacarmenpozo@hotmail.com', '0'),
  ('rodriguezvillarmariano1@gmail.com', 'Anaïs Rodriguez Bastiani', '13343674V', '2012-01-11', 'Calle Pedro Alonso 11', 'S', 'JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '671743812', 'rodriguezvillarmariano1@gmail.com', '440'),
  ('inamaris.mkt@gmail.com', 'Andreína Maris', '60132947E', '1995-12-24', 'Calle Del Pozo nuevo 19, 2C, 28430 Alpedrete', 'S', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '643121348', 'inamaris.mkt@gmail.com', '440'),
  (null, 'Angelina De La Rua Mazza', '07162401V', '2017-01-14', 'antilope 3 piso 1 c Guadarrama', '10.0', 'JUEVES 18h', null, null, '620781903', 'eleonoramazza0382@gmail.com', '440'),
  ('antoniogilromero@gmail.com', 'Antonio carlos Gil Romero', '50120015w', '1979-10-21', 'Soria 8 Guadarrama', 'Xl', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '605808150', 'Antoniogilromero@gmail.com', '0'),
  ('Victor_pv32@yahoo.es', 'Bruno Pasamontes alarcon', '05734248A', '2016-05-28', 'Travesía Arroyo de los Sauces 9 3-2 alpedrete', 'S', 'MARTES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '659295685', 'Victor_pv32@yahoo.es', '440'),
  ('irenelostau@gmail.com', 'Carlos Pereda Lostau', '72340074Z', '2018-03-30', 'Calle Las Pozas 118 Portal 4 3º dcha del bajo San Lorenzo del Escorial', '8 años', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '660781215', null, '440'),
  ('kickers91@yahoo.ea', 'Carolina Sánchez perez', '51085896k', '1979-03-02', 'Avenida de Cierros13', 'S', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', null, '622262233', 'kickers91@yahoo.ea', '300'),
  ('irenelostau@gmail.com', 'Celia Pereda Lostau', '72285571K', '2015-02-23', 'Calle Las Pozas 118 Portal 4 3º dcha del bajo San Lorenzo del Escorial', 'XS', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '660781215', null, '440'),
  ('susanvelasco@hotmail.com', 'Cleoma Bonvalet', '03175535V', '2012-10-03', 'C Primavera 19 alpedrete', 'xs', 'MARTES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '687460385', 'susanvelasco@hotmail.com', '440'),
  ('pablobarez@gmail.com', 'Daniel Bárez Carballo', '50585335D', '2011-10-25', 'Prado, 11 MORALZARZAL', 'M', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '679 458 342', 'pablobarez@gmail.com', '440'),
  ('dcastromar@gmail.com', 'Daniel Castro Márquez', '51115334L', '1993-08-25', 'calle de la jara 9 collado mediano', 'M', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', null, null, '440'),
  ('d.puchehontanilla@gmail.com', 'Daniel Puche Hontanilla', '02547508M', '1974-03-22', 'Calle la Tejera 28.Becerril de la Sierra', 'L', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '661978164', 'd.puchehontanilla@gmail.com', '440'),
  ('elen_mac@yahoo.es', 'david de lorenzo Macías', '51082273d', '2015-03-01', 'Jardin castores 7 cerceda', '12 años', 'JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'No autorizo el uso de mi imagen (o la de mi hij@)', '676240051', 'elen_mac@yahoo.es', '440'),
  ('deiopasp@gmail.com', 'David del Río Pascual', '46936833C', '1978-08-26', 'Av Vigo 29 alpedrete', 'M', 'MARTES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '609347383', 'driopasp@gmail.com', '300'),
  ('diegogilgordillo@gmail.com', 'Diego Gil  Gordillo', '01938631F', '2008-10-01', 'Calle Soria 8, Guadarrama', 'M', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '625367351', 'diegogilgordillo@gmail.com', '440'),
  ('elena.perez.arrow@gmail.com', 'Elena Perez Ruiz', '52991006H', '1976-05-11', 'balconada 7 Collado Villalba', 'M', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '667037410', null, '300'),
  ('pablobarez@gmail.com', 'Eloy Bárez Carballo', '52053316S', '2015-07-10', 'Calle Prado, 11 Moralzarzal', '12 años', null, 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'No autorizo el uso de mi imagen (o la de mi hij@)', '679 458 342', 'pablobarez@gmail.com', '440'),
  ('fernandobernal.es@bermad.com', 'Fernando Bernal Salve', '06267683E', '1982-03-27', null, 'M', 'MARTES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '671 008 930', 'Fernandobernal.es@bermad.com', '300'),
  ('fernando@nimar.es', 'Fernando Niño Martínez', '50196358P', '1973-11-03', 'Avda. Eras, 18 - 1C collado villalba', 'M', 'MARTES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '615603544', 'fernando@nimar.es', '300'),
  ('rcg1917@gmail.com', 'Gorka Hernando Muñoz', '70286530W', '2013-03-05', 'Calle Julio Atienza 2 Portal 3 Primero P collado villalba', 'M', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '665698846', 'rcg1917@gmail.com', '440'),
  ('teresa.serralta@gmail.com', 'Guillermo González Serralta', '06705960B', '2013-08-29', 'Camino de los boquerones 17 Guadarrama', 'S', 'MARTES, JUEVES', null, null, null, null, '440'),
  (null, 'Guillermo Simon Perez', '14306715w', '1979-06-16', 'balconada 7 Collado Villalba', 'xl', null, null, null, null, null, '0'),
  (null, 'Hector Javier de la calle Gonzalez', '51395480w', '1968-08-08', 'Mediterraneo 41 Alpedrete', 's', null, null, null, null, 'llitomtb@gmail.com', '0'),
  ('cris_ocana@hotmail.com', 'Hugo Jiménez Ocaña', '51817982V', '2015-10-25', 'Calle Gustavo Adolfo Becquer 2, Moralzarzal', '14.0', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '616690492', 'cris_ocana@hotmail.com', '440'),
  ('hugo.martin.rodao.entrenador@gmail.com', 'Hugo Martin Rodao', '70280035Q', '2003-04-19', 'Doctor Varela 25, D, Bjo B alpedrete', 'L', 'MARTES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '684261471', 'hugo.martin.rodao.entrenador@gmail.com', '440'),
  ('mgonzalezmartin77@gmail.com', 'Hugo Ramos Gonzalez', '11088980J', '2013-10-25', 'La Torre, 3 Guadarrama', 'S', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '660420634', 'mgonzalezmartin77@gmail.com', '440'),
  ('elena.perez.arrow@gmail.com', 'Hugo Simon Perez', '70278215J', '2013-07-20', 'balconada 7 Collado Villalba', 'L', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '669550946', null, '440'),
  ('pjwsimpson82@gmail.com', 'Isabel Simpson', '71320772A', '2011-11-28', 'calle Collado mediano 12    1 b Alpedrete', 'S', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '649458272', 'pjwsimpson82@gmail.com', '440'),
  (null, 'Isabella D''Addiego', 'Y8643342W', '2011-04-11', 'Jarosa 1 28 Piso 3 C Guadarrama', 'M', '6.33083661E8', null, null, '633083661', 'isabelladaddiego11@gmail.com', '300'),
  ('mlcontonente@yahoo.es', 'JAIME CONTRERAS LOPEZ', '06687040C', '2011-06-17', 'C/ FEDERICO GARCIA LORCA 19, MORALZARZAL 28411 (MADRID)', 'S', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '680171915', 'mlcontonente@yahoo.es', '440'),
  ('jgm-83@hotmail.com', 'Jaime González Marcos', '50119629F', '1983-03-11', 'C/Cuarta dimension 18 Guadarrama', 'L', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '686914849', 'jgm-83@hotmail.com', '440'),
  ('kickers91@yahoo.ea', 'Jara Lahera Sánchez', '54888085b', '2014-05-23', 'Avenida de Cierros 13 El Escorial', '12 años', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '622262233', 'kickers91@yahoo.ea', '440'),
  ('javiercerdeira@hotmail.com', 'JAVIER CERDEIRA MELERO', '01924504W', '1972-10-14', 'Calle Felipe V, 11 - El Escorial. 28280 Madrid', 'M', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '661450388', 'javiercerdeira@hotmail.com', '440'),
  (null, 'JAVIER GIL ROMERO', null, '1986-01-06', null, 'l', null, null, null, null, null, '0'),
  ('jesusegeamanjavacas@gmail.com', 'Jesús Egea Manjavacas', '50356014K', '2009-03-24', 'navalcarnero', 'L', 'MARTES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '690138392', 'jesúsegeamanjavacas@gmail.com', '0'),
  ('millohandmade@hotmail.com', 'Joaquín Millo Acedo', '02245246d', '1973-03-07', 'Manantiales 2  collado mediano', 'M', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '679750831', 'millohandmade@hotmail.com', '300'),
  ('wynnys@hotmail.com', 'Jorge del Río Serrano', '53301381P', '2015-05-20', 'Avda de Vigo 29 alpedrete', 'XS', 'MARTES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '636212702', 'wynnys@hotmail.com', '440'),
  (null, 'Jose Ignacio lledo León', '02669439j', '1983-12-20', 'frayernidad 28 collado villalba', 's', null, null, null, null, 'nach.2012@gmail.com', '0'),
  ('jl.mvg.pl@gmail.com', 'José Luis Martín-VelascoGutiérrez', '03891725X', '1978-06-01', 'Calle Roma 3, portal 3, 1D, Alpedrete, Madrid', 'L', 'JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '629428920', 'jl.mvg.pl@gmail.com', '440'),
  ('joseluis.plaza@uam.es', 'José Luis Plaza Canga-Arguelles', '50846979M', '1971-05-09', 'Calle Pradillos 66 moralzarzal', 'L', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '616153848', 'joseluis.plaza@uam.es', '440'),
  (null, 'juan aparicio Manzano', '70050191b', '1977-07-07', 'ciudad real 11 Guadarrama', 'l', null, null, null, '652813837', 'juanapaman@gmail.com', '0'),
  ('jmrdepablo@hotmail.com', 'Juan Manuel Rodriguez de Pablo', '50099816C', '1978-11-09', 'C/Villas de Guadarrama,16', 'L', null, 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '650978578', 'jmrdepablo@hotmail.com', '0'),
  ('millohandmade@hotmail.com', 'Julia Millo Bretin', '12842615J', '2011-07-15', 'Manantiales 2 collado mediano', 'S', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '679750831', 'millohandmade@hotmail.com', '440'),
  ('l.dediego.gustin@gmail.com', 'Lara de Diego Gustin', '70066907Y', '1996-04-25', 'Calle Santa Clara 45, bloque B, piso 2A, San Lorenzo de El Escorial', 'L', 'JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '610991110', 'L.dediego.gustin@gmail.com', '440'),
  ('mamin81_@hotmail.com', 'Lola López Moreno', '55526823q', '2018-06-30', 'Calle perdón 47 Collado Villalba 28400', '8.0', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '678417269', null, '440'),
  (null, 'Lorenzo Bernal Carpio', '06270331W', '2018-11-18', 'Calle Auseva,13 28248 La Berzosa', '8.0', 'MARTES, JUEVES', null, 'TRIATLON', 'ferbernal1982@hotmail.com', null, '440'),
  (null, 'Lucas Bernardo Strumbo', 'X6797419E', '1989-03-15', 'Altos de la Jarosa 6, bloq 3, num 6, Guadarrama 28440, Madrid', 'XL', null, null, null, null, 'strumbolucas@gmail.com', '300'),
  ('elena.perez.arrow@gmail.com', 'Lucia Simon Perez', '06637908Q', '2013-12-28', 'balconada 7 Collado Villalba', 'L', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '630529800', null, '440'),
  ('lcerrilloa@gmail.com', 'Luis Cerrillo Arias', '50720624N', '1968-11-17', 'Cl Molineras 9 cercedilla', 'L', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '722504781', 'lcerrilloa@gmail.com', '440'),
  ('lmblazquez2@hotmail.com', 'Luis Miguel Blázquez Iznaol', '50196253h', '1975-02-20', 'Calle Gregorio Marañon 23 alpedrete', 'XL', 'MARTES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '629825367', 'lmblazquez2@hotmail.com', '440'),
  ('teresa.serralta@gmail.com', 'Luna González Serralta', '06705961N', '2017-08-13', 'Camino de los boquerones 17 Guadarrama', '8.0', 'MARTES, JUEVES', null, null, null, null, '440'),
  ('manuel.arenas87@hotmail.com', 'Manuel Arenas Mateos', '70064731s', '1987-12-03', 'Paseo de los Tilos 10 guadarrama', 'L', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '635231229', 'manuel.arenas87@hotmail.com', '440'),
  ('rafaelcaballerodelacruz@gmail.com', 'María Caballero de la Cruz', '51770781N', '2012-07-10', 'Urb. La Cerca 5 Collado Villalba', 'XS', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '722185017', 'rafaelcaballerodelacruz@gmail.com', '440'),
  ('pjwsimpson82@gmail.com', 'María Simpson', '06645660V', '2015-06-09', 'collado mediano 12 piso 1 b Alpedrete', '10 años', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '605902340', 'pjwsimpson82@gmail.com', '440'),
  ('tejerobarcoenrique@gmail.com', 'Mario tejero maria', '08932134S', '2019-01-04', 'Calle cabeza mediana 9 collado mediano', '10 años', 'JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '696472817', 'Tejerobarcoenrique@gmail.com', '440'),
  ('mgonzalezmartin77@gmail.com', 'Marta Gonzalez Martin', '50741073Z', '1977-05-07', 'La Torre, 3 Guadarrama Madrid', 'S', 'JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '660420634', 'mgonzalezmartin77@gmail.com', '300'),
  ('diegoarribas1978@gmail.com', 'Martín Arribas del Amo', '05732079L', '2015-06-13', 'c/ San Sebastián nº24 Bloque 1 1º C El Boalo Madrid', 'S', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '627504384', 'diegoarribas1978@gmail.com', '440'),
  ('peques141405@gmail.com', 'Martina Pous Ribagorda', '53362278F', '2011-08-05', 'Nogal 5. Guadarrama', 'M', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '620809905', 'peques141405@gmail.com', '440'),
  ('mangelcontreras@yahoo.es', 'Miguel Angel Contreras Contreras', '02623141Z', '1974-06-05', 'Federico Ga4cia Lorca 19 moralzarzal', 'M', 'MARTES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '690886692', 'Mangelcontreras@yahoo.es', '300'),
  ('sodepra@hotmail.com', 'Miguel Ángel Pedrosa Hiruelas', '52872415S', '1977-09-24', 'C/ San Lorenzo, 4 guadarrama', 'L', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '655446683', 'sodepra@hotmail.com', '440'),
  ('ndelisrojas@gmail.com', 'Nimai Pandit Delis Rojas', '06613039X', '2006-07-03', 'Collado Mediano, Calle de las eras 9', 'M', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '640194979', 'ndelisrojas@gmail.com', '0'),
  (null, 'Noa Lopez Herrera', '05732618Y', '2015-09-12', 'Calle Mediterráneo 54 alpedrete', '14 años', '6.30757167E8', 'JUEVES', 'TRIATLON', 'josete9@hotmail.com', 'Josete9@hotmqil.com', '440'),
  ('noemiconacento1@hotmail.com', 'Noemí de la Cuerda', '46866753K', '1975-08-23', 'palencia 6 piso 1  4 COLLADO MEDIANO', 'S', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '629571948', 'noemiconacento1@hotmail.com', '440'),
  ('palomacanalesespi28@gmail.com', 'Paloma Canales Espi', '70068891N', '1999-11-25', 'Paseo de los Tilos 10 guadarrama', 'M', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '630336470', 'palomacanalesespi28@gmail.com', '440'),
  ('paurnamasihps@gmail.com', 'Paloma Rojas Vaquero', '50175820D', '1976-06-04', 'calle Eras Collado Mediano', 'M (hombre) L (mujer)', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '644405484', 'paurnamasihps@gmail.com', '440'),
  ('paula.holguin.guadarrama@gmail.com', 'Paula Holguín Segovia', '11086228K', '1999-11-15', 'Calle río tajo 35 1b guadarrama', 'M', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '626149901', 'paula.holguin.guadarrama@gmail.com', '440'),
  ('paula.rubio1290@gmail.com', 'Paula Rubio Sutil', '01854448G', '2008-10-29', 'calle san lorenzo 28 alpedrete', 'S', '6.4413476E8', null, null, '644134760', 'paula.rubio1290@gmail.com', '360'),
  ('pjwsimpson82@gmail.com', 'Peter Simpson', 'X9818047Z', '1982-08-09', 'calle Collado mediano 12    1 b Alpedrete', 'L', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '605902340', 'pjwsimpson82@gmail.com', '300'),
  ('mamin81_@hotmail.com', 'Quique López Moreno', '55526824V', '2014-12-29', 'Calle perdón 47 collado villalba', '12.0', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '678417269', null, '440'),
  ('rafaelcaballerodelacruz@gmail.com', 'Rafael Caballero de la Cruz', '01934577R', '1979-08-02', 'Urbanización la cerca 5 Collado Villalba', 'L', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '722185017', 'rafaelcaballerodelacruz@gmail.com', '300'),
  ('raquelgg84@hotmail.com', 'Raquel Gómez García', '03118929Z', '1984-05-08', 'Calle A Coruña número 9 Alpedrete', 'S', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '660040550', 'raquelgg84@hotmail.com', '300'),
  ('rosanegreirahdez@gmail.com', 'Rosa Negreira Hernandez', '50545796F', '1984-10-27', 'Avda Eras 18 - 1C - 28400 Collado Villalba', 'S', 'JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '686010277', 'rosanegreirahdez@gmail.com', '300'),
  (null, 'Rosa Strumbo Wilson', '54891943M', '2017-08-11', 'Altos de la Jarosa 6, bloq 3, num 6, Guadarrama 28440, Madrid', '8 años', '6.18713331E8', 'MARTES', 'DUATLON', 'lauraibanezwilson@gmail.com', 'Laura', '440'),
  ('planetasandra@gmail.com', 'Sandra Machado Henares', '33515671w', '1972-08-08', 'Avda Meridiana, 13 guadarrama', 'M', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '609069602', 'planetasandra@gmail.com', '440'),
  ('paurnamasihps@gmail.com', 'Sarasvati Delis Rojas', '51259743B', '2013-09-15', 'calle Eras Collado Mediano', '13 años', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '623998291', null, '440'),
  ('-', 'Saúl Niño Negreira', '15468561A', '2017-06-19', 'Avda. Eras, 18 - 1C - 28400 Collado Villalba', '10.0', 'JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '615603544', 'fernando@nimar.es', '440'),
  ('rebeca_alonso_parra@yahoo.es', 'Saul Tabasco Alonso', '05731655D', '2013-01-04', 'Calle Doctor Andrés Hernández 21 Moralzarzal', 'S', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '699478462', 'saultabascotriatleta@gmail.com', '440'),
  (null, 'Sergio San Fruto Conde', '70269642L', '2005-03-01', 'Calle la oliva 2 chalet 10 cercedilla', 'xl', 'MARTES,JUEVES', null, null, '680512415', null, '300'),
  ('soniaandresconde75@gmail.com', 'Sonia Andres Conde', '05428175z', '1975-03-17', 'Calle la oliva 2 chalet 10 cercedilla', 'L', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '620536879', 'soniaandresconde75@gmail.com', '440'),
  ('soniacesteros@gmail.com', 'Sonia Cesteros Garcia', '51109558Q', '1989-10-19', 'Soria 8 Guadarrama', 'S', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', null, null, '0'),
  ('teresa.sancho.hernandez@gmail.com', 'Teresa Sancho Hernández', '46894161J', '1984-09-11', 'Calle Montevideo 11 5d Móstoles', 'S', null, 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '686637764', 'Teresa.sancho.hernandez@gmail.com', '440'),
  ('teresaserralta@gmail.com', 'Teresa Serralta Gely', '05315497J', '1988-04-27', 'Camino de los boquerones 17 Guadarrama', 'L', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '680 95 88 94', null, '300'),
  ('ddelgadopaula@gmail.com', 'TULIO RUIZ DELGADO', '08015664A', '2018-01-15', 'calle madre paula montal 2 los molinos', '8 años', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '681308115', 'ddelgadopaula@gmail.com', '440'),
  ('helikrisum@yahoo.es', 'Vega Delgado de Felix', '06721797R', '2015-04-27', 'C/Laurel, 76, Cerceda', '14.0', 'JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'No autorizo el uso de mi imagen (o la de mi hij@)', '657922206', 'helikrisum@yahoo.es', '440'),
  ('sergio.sanfrutos@gmail.com', 'Sergio San Frutos', '70269642L', '2005-03-01', 'Calle la Oliva 2, chalet 10', 'L', 'MARTES, JUEVES', 'Acepto la política de privacidad y doy mi consentimiento para que el C.D.E  Triatlón Alpedrete trate mis datos exclusivamente para la gestión deportiva y administrativa del club.', 'SI autorizo al club a publicar imágenes/vídeos donde aparezca (mi hij@ si es menor de edad) en las web, redes sociales y comunicaciones oficiales del club con fines informativos o promocionales', '680512415', 'sergio.sanfrutos@gmail.com', null),
  ('lauraibanezwilson@gmail.com', 'Leon Strumbo Wilson', '54891943M', '2017-08-11', 'Altos de la Jarosa 6, bloq 3, num 6, Guadarrama 28440, Madrid', '6.0', 'MARTES', null, null, '618713331', 'Laura', '300'),
  (null, 'Ramón Hernando', null, null, null, 'L', null, null, null, '665698846', null, '300'),
  (null, 'David Fernández Álvarez', '52974831N', '1978-08-23', 'Calle Vereda del Colmenar 8 BjD', 'M', 'MARTES, JUEVES', null, null, '646632587', 'davidcbr98@hotmail.com', '440')
)
insert into inscripciones (email, nombre_completo, dni, fecha_nacimiento, domicilio,
  talla_camiseta, dias_piscina, proteccion_datos, derechos_imagen, telefono, email2, tarifa)
select d.email, d.nombre_completo, d.dni, d.fecha_nacimiento::date, d.domicilio,
  d.talla_camiseta, d.dias_piscina, d.proteccion_datos, d.derechos_imagen, d.telefono, d.email2, d.tarifa
from datos d
where not exists (
  select 1 from inscripciones i
  where unaccent(lower(i.nombre_completo)) = unaccent(lower(d.nombre_completo))
);

select count(*) as inscripciones_totales from inscripciones;
